apiVersion: v1
kind: PersistentVolume
metadata:
  name: config-volume
spec:
  capacity:
    storage: 2Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: standard
  # hostPath: # Not good in product
  #   - ~/projects/KeyValueAndKube/k8s/scripts
