apiVersion: v1
kind: PersistentVolume
metadata:
  name: config-volume
spec:
  capacity:
    storage: 2Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: standard
