apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-volume
spec:
  storageClassName: standard
  resources:
    requests:
      storage: 3Mi
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  # hostPath: # Not good in product
  #   - ~/projects/KeyValueAndKube/k8s/scripts
