---
# mongo config server
apiVersion: apps/v1beta1
kind: StatefulSet
serviceName: mongodb-configdb-service
metadata:
  name: mongod-configdb
spec:
  replicas: 2
  containers:
  - name: mongod-configdb-container
    image: mongo
    command:
      - "mongod"
      - "--port"
      - "27017"
      - "--configsvr"
      - "--replSet configserver"
---
# expose config servers
apiVersion: v1
kind: Service
metadata:
  name: mongodb-configdb-service
  labels:
    name: mongo
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    name: mongos
