---
# following configuration is recommended by the mongodb page
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: key-value-db
  namespace: myserver # match the configmap file
spec:
  shardCount: 2 # 2 shards
  mongodsPerShardCount: 3 # 3 daemon controllers / shard
  mongosCount: 2 # mongo router count
  configServerCount: 3
  version: 4.0.6
  project: key-value-configmap # Should match metadata.name in your
                         # configmap file.
  # credentials: <mycredentials>
  type: ShardedCluster
  persistent: true
  # # for tls
  # security:
  #   tls:
  #     enable: true
  #   clusterAuthenticationMode: x509
  #   AdditionalMongodConfig:
  #     net:
  #       ssl:
  #         mode: requireSSL # only accept TLS connection, other mode preferSSL, allowSSL
  # # for resources:
  # ConfigSrvPodSpec:
  #   cpu:
  #   cpuRequests:
  #   memory:
  #   memoryRequests:
  #   nodeAffinity:
