---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongod-configdb
spec:
  serviceName: "mongodb-configdb-service"
  replicas: 2
  selector:
    matchLabels:
      name: mongod-configdb
  template:
    metadata:
      name: mongod-configdb
      labels:
        name: mongod-configdb
    spec:
      containers:
      - name: mongod-configdb-container
        image: mongo
        command:
          - "mongod"
          - "--port"
          - "27017"
          - "--configsvr"
          - "--replSet"
          - "configserver"
          - "--bind_ip_all"
        volumeMounts:
          - name: config-volume
            mountPath: /config
      volumes:
        - name: config-volume # mutal volume containning config scripts
          persistentVolumeClaim:
            claimName: config-volume
---
# expose config servers
apiVersion: v1
kind: Service
metadata:
  name: mongodb-configdb-service
  labels:
    name: mongo-configdb
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    name: mongod-configdb
