---
# mongo router
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongos
  labels:
    name: mongos
spec:
  replicas: 2
  selector:
    matchLabels:
      name: mongos
  template:
    metadata:
      labels:
        name: mongos
    spec:
      containers:
        - name: mongos-container
          image: mongo
          volumeMounts:
            - name: config-volume
              mountPath: /config
          command:
            - "mongos"
            - "--port"
            - "27017"
            - "--bind_ip_all"
            - "--configdb"
            - "configserver/mongod-configdb-0.mongodb-configdb-service.myserver.svc.cluster.local:27017,mongod-configdb-1.mongodb-configdb-service.myserver.svc.cluster.local:27017" # add all configserver to each router
          ports:
            - containerPort: 27017
---
# to expose mongo-router
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    name: mongo
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    name: mongos
