---
# mongo shards
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-shard0
  labels:
    name: mongo-shard0
spec:
  serviceName: "shard0-service"
  replicas: 1 # for simplicy, without creating many volume
  selector:
    matchLabels: # This will search for matched pod's label having matched 'name' value in the 'set of labels'
      name: mongo-shard0
  template:
    metadata:
      name: mongo-shard0
      labels:
        name: mongo-shard0
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo
          command:
            - "mongod"
            - "--port"
            - "27017"
            - "--shardsvr"
            - "--replSet"
            - "shard0"
            - "--bind_ip_all" # to listen on all available network interface
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: my-db-storage
              mountPath: /data/db
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          persistentVolumeClaim:
            claimName: config-volume
  volumeClaimTemplates:
  - metadata:
      name: my-db-storage
      # annotations:
      #   volume.beta.kubernetes.io/storage-class: "ssd"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: 2Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-shard1
  labels:
    name: mongo-shard1
spec:
  serviceName: "shard1-service"
  replicas: 1 # for simplicy, without creating many volume
  selector:
    matchLabels: # TODO: Explore more about this selector's selection behavior
      name: mongo-shard1
  template:
    metadata:
      name: mongo-shard1
      labels:
        name: mongo-shard1
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo
          command:
            - mongod
            - "--port"
            - "27017"
            - "--shardsvr"
            - "--replSet"
            - "shard1"
            - "--bind_ip_all"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: my-db-storage
              mountPath: /data/db
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          persistentVolumeClaim:
            claimName: config-volume
  volumeClaimTemplates:
  - metadata:
      name: my-db-storage
      # annotations:
      #   volume.beta.kubernetes.io/storage-class: "ssd"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: 2Gi
---
# shard services
# to expose mongo-router
apiVersion: v1
kind: Service
metadata:
  name: shard0-service
  labels:
    name: shard0-service
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    name: mongo-shard0
---
apiVersion: v1
kind: Service
metadata:
  name: shard1-service
  labels:
    name: shard1-service
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    name: mongo-shard1
